language: r

r_binary_packages:
 - dplyr
 - magrittr


after_failure:
  - ./travis-tool.sh dump_logs

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
